# 以下为 githubpage上不可修改的参数，见https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll
#lsi: false # 为相关文章生成索引
#safe: true # 禁用自定义插件
#source: [your repo's top level directory] # Jekyll 读取文件的路径
#incremental: false # 增量生成
#highlighter: rouge # 代码高亮器
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge

# 以下为githubpage默认开启的插件，见https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
#plugins:
#  - jekyll-github-metadata
#  - jekyll-coffeescript
#  - jekyll-default-layout
#  - jekyll-gist
#  - jekyll-github-metadata
#  - jekyll-optional-front-matter
#  - jekyll-paginate
#  - jekyll-readme-index
#  - jekyll-titles-from-headings
#  - jekyll-relative-links

# repository: wu-kan/wu-kan.gitub.io
# 以下是github会自动生成的配置项，见https://jekyll.github.io/github-metadata/site.github/
#github:
#{
#    "versions": {
#        "jekyll": <version>,
#        "kramdown": <version>,
#        "liquid": <version>,
#        "maruku": <version>,
#        "rdiscount": <version>,
#        "redcarpet": <version>,
#        "RedCloth": <version>,
#        "jemoji": <version>,
#        "jekyll-mentions": <version>,
#        "jekyll-redirect-from": <version>,
#        "jekyll-sitemap": <version>,
#        "github-pages": <version>,
#        "ruby": <version>"
#    },
#    "hostname": "github.com",
#    "pages_hostname": "github.io",
#    "api_url": "https://api.github.com",
#    "help_url": "https://help.github.com",
#    "environment": "dotcom",
#    "pages_env": "dotcom",
#    "public_repositories": [ Repository Objects ],
#    "organization_members": [ User Objects ],
#    "build_revision": "cbd866ebf142088896cbe71422b949de7f864bce",
#    "project_title": "metadata-example",
#    "project_tagline": "A GitHub Pages site to showcase repository metadata",
#    "owner_name": "github",
#    "owner_url": "https://github.com/github",
#    "owner_gravatar_url": "https://github.com/github.png",
#    "repository_url": "https://github.com/github/metadata-example",
#    "repository_nwo": "github/metadata-example",
#    "repository_name": "metadata-example",
#    "zip_url": "https://github.com/github/metadata-example/zipball/gh-pages",
#    "tar_url": "https://github.com/github/metadata-example/tarball/gh-pages",
#    "clone_url": "https://github.com/github/metadata-example.git",
#    "releases_url": "https://github.com/github/metadata-example/releases",
#    "issues_url": "https://github.com/github/metadata-example/issues",
#    "wiki_url": "https://github.com/github/metadata-example/wiki",
#    "language": null,
#    "is_user_page": false,
#    "is_project_page": true,
#    "show_downloads": true,
#    "url": "http://username.github.io/metadata-example", // (or the CNAME)
#    "baseurl": "/metadata-example",
#    "contributors": [ User Objects ],
#    "releases": [ Release Objects ],
#    "latest_release": [ Release Object ],
#    "private": false,
#    "archived": false,
#    "disabled": false,
#    "license": {
#      "key": "mit",
#      "name": "MIT License",
#      "spdx_id": "MIT",
#      "url": "https://api.github.com/licenses/mit"
#    },
#    "source": {
#      "branch": "gh-pages",
#      "path": "/"
#    }
#}

# 以下四个配置项为空时jekyll-github-metadata会帮你生成
title: wu-kan
description: | # 不知道怎么写介绍，放个音乐吧
  <iframe
    src="//music.163.com/outchain/player?type=0&id=155059595&auto=0&height=32"
    width=100%
    height=52
    frameborder="no"
    border="0"
    marginwidth="0"
    marginheight="0"
  ></iframe>
url: https://wu-kan.cn # https://wu-kan.github.io
baseurl: "" # 假如你的博客是建在某个目录下的，请在这里加上目录名，并且下面配置的所有链接里的`/assets`前也要加，即`/your_baseurl/assets`。这一项结尾不要有'/'。

# 移植中！见https://github.blog/2017-11-29-use-any-theme-with-github-pages/，这一项不要改
remote_theme: wu-kan/wu-kan.github.io

markdown: kramdown
kramdown: # 见https://kramdown.gettalong.org/options.html
  input: GFM # 见http://jekyllcn.com/docs/configuration/#kramdown
  syntax_highlighter_opts: # 可见https://kramdown.gettalong.org/syntax_highlighter/rouge.html
    disable: true # 关掉默认的高亮，换用prismjs

permalink: /_posts/:year-:month-:day-:title/
author:
  name: WuK
  email: wu.kan@foxmail.com
timezone: Asia/Shanghai # 解决githubpage显示时间不正确的问题，见https://www.iana.org/time-zones
future: false # 不发布时间在未来的文章

# limit_posts: 999 # 限制博文数量
# encoding: utf-8

index:
  show:
    recent:
      enable: true
      title: Recent
      limit: 5
      archive:
        enable: true
        href: /archive
        alert: posts in total ...
    categories:
      - 博客搭建
    tags:
      - 人生经验
      - ICPC模板
      - 水野爱

page404:
  head: | # 腾讯公益
    <script
      src='//qzonestyle.gtimg.cn/qzone/hybrid/app/404/search_children.js'
      defer='defer'
      charset='utf-8'
      homePageUrl='/'
      homePageName='回到我的主页'
    ></script>

merger: # 支持的变量见https://merger.justhx.com/cn/docs/configure
  head: |
    <meta
      charset="utf-8"
    />
    <meta
      name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />
    <meta
      http-equiv="Content-Security-Policy"
      content="upgrade-insecure-requests"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/combine/gh/hifocus/merger@0.21.1/assets/styles/spectre.css/spectre-modified.min.css,gh/hifocus/merger@0.21.1/assets/styles/style.min.css"
    />
    <script
      src='//cdn.jsdelivr.net/combine/gh/hifocus/merger@0.21.1/assets/js/jQuery/jquery.min.js,gh/hifocus/merger@0.21.1/assets/js/jquery-qrcode/jquery-qrcode.min.js,gh/hifocus/merger@0.21.1/assets/js/JavaScript_MD5/md5.min.js,gh/hifocus/merger@0.21.1/assets/js/function.min.js,gh/hifocus/merger@0.21.1/assets/js/font_974919_xgtacm93vxp.min.js'
      defer='defer'
    ></script>
    <script>
      var usage = "payment";
      var wechat = "wxp://f2f0BhUoIC_9gex7-tC2PRvVuoA486mK5WyC";
      var tenpay = "https://i.qianbao.qq.com/wallet/sqrcode.htm?m=tenpay&f=wallet&a=1&ac=CAEQ77zFwQMY-6u57gU%3D_xxx_sign&u=942759535&n=%E8%94%9A";
      var alipay = "https://qr.alipay.com/fkx02750b5kbplxvudqrx16";
      var paypal = "https://paypal.me/wukan0621";
      var myname = "WuK";
      var profile = "//gravatar.loli.net/avatar/a12c5fff23dde00df79af9aca4e7b6e4?s=300";
      var multilingual = true;
      var myname_hans = "吴坎";
      var myname_hant = "吴坎";
      var myname_eng = "WuK";
      var title = "选择你的支付方式";
      var subtitle = "跟随进一步的指示以向" + myname + "付款";
      var qrcodeapi = "https://www.zhihu.com/qrcode?url=";
    </script>

archive:
  posts_count:
    enable: true
    alert: 篇博文。长路漫漫！

comments:
  valine: true # 需要在script中引入

post:
  date:
    enable: true
    alert: <i class="fas fa-calendar-day"></i>
  wordcount:
    enable: true
    alert: <i class="fas fa-file-word"></i>
    unit: 字
  readtime:
    enable: true
    alert: <i class="fas fa-book-open"></i>
    unit: 分
    divided_by: 300
  visitor: # 需要引入并开启valine的visitor选项使之开始计数; 可能会和busuanzi统计的有出入
    enable: true
    alert: <i class="far fa-eye"></i>
    unit: 次
  categories:
    enable: true
    alert: <i class="fas fa-th"></i>
  tags:
    enable: true
    alert: <i class="fas fa-tag"></i>
  copyright: |
    <br/>
    <i class="fab fa-creative-commons"></i>
    <a rel="license" href="//creativecommons.org/licenses/by-sa/4.0/deed.zh">BY-SA 4.0</a>（除特别声明或转载文章外）
    <br/>
    <i class="fas fa-coffee"></i>
    <a href="/merger/">如果这篇博客帮助到你，可以请我喝一杯咖啡~</a>

page:
  body:
    theme-base: theme-base-0d # 可选的值08~0f
    layout-reverse: false # 开启后sidebar在右边，反之左边
    sidebar-overlay: false # 开启后正文不随sidebar移动而移动
  sidebar:
    avatar: # 侧边栏显示的头像
      enable: true
      img: //gravatar.loli.net/avatar/a12c5fff23dde00df79af9aca4e7b6e4?s=300 # 头像的地址
      info: | # 头像背后的信息，<br/>代表换行
        <br/>SYSU17级在读
        <br/>计科超算方向
        <br/>永远喜欢水野爱
        <br/>田宫例四驱车
        <br/>ASC
    social:
      - title: rss
        href: /assets/jekyll-sitemaps/atom.xml
        class: "fas fa-rss"
      - title: wu.kan@foxmail.com # email
        href: mailto:wu.kan@foxmail.com
        class: "fas fa-envelope"
      - title: github
        href: //github.com/wu-kan
        class: "fab fa-github"
      - title: WuK # codeforces
        href: //codeforces.com/profile/WuK
        class: "fas fa-chart-bar fw"
      - title: WuK # vjudge
        href: //vjudge.net/user/WuK
        class: "fas fa-smile"
      - title: 942759535 # qq
        class: "fab fa-qq"
      - title: Wu-_-Kan # weixin
        class: "fab fa-weixin"
      - title: zhihu
        href: //www.zhihu.com/people/wu.kan/activities
        class: "fab fa-zhihu"
    nav:
      - title: '<i class="fas fa-home fa-fw"></i> 首页'
        href: /
      - title: '<i class="fab fa-readme fa-fw"></i> 关于'
        href: /about/
      - title: '<i class="fas fa-comments fa-fw"></i> 留言'
        href: /comments/
      - title: '<i class="fas fa-tags fa-fw"></i> 标签'
        href: /tags/
      - title: '<i class="fas fa-archive fa-fw"></i> 归档'
        href: /archive/
      - title: '<i class="fas fa-coffee fa-fw"></i> 打赏'
        href: /merger/
    simple_jekyll_search:
      enable: true
      placeholder: 搜索博文
      full_text_search: false # 可能导致缓慢的搜索和加载
    jekyll_table_of_contents: true #需要脚本中引入
    busuanzi:
      enable: true
      page_pv: # 页面访问量
        alert: <i class="fas fa-eye fa-fw"></i>
        unit: 次
      site_pv: # 站点访问量
        alert: <i class="fas fa-paw fa-fw"></i>
        unit: 枚
      site_uv: # 访客量
        alert: <i class="fas fa-user-friends fa-fw"></i>
        unit: 人
    wordcount:
      enable: true
      alert: <i class="fas fa-user-edit fa-fw"></i>
      kilo: 千
      unit: 字
    last_edit:
      enable: true
      alert: <i class="fas fa-edit fa-fw"></i>
    run_time:
      enable: true
      start_time: "10/04/2017 11:03:56" # 这是我第一篇CSDN博客的时间
      alert: <i class="fas fa-cog fa-spin fa-fw"></i>
      day: 天
      hour: 时
      minute: 分
      second: 秒
    copyright:
      enable: true
      text: |
        <a
          class="github-button"
          aria-label="Star wu-kan/wu-kan.github.io on GitHub"
          href="https://github.com/wu-kan/wu-kan.github.io" data-icon="octicon-star" data-show-count="true"
        >Star</a>
  head: |
    <base
      target="_blank"
    />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1"
    />
    <meta
      http-equiv="X-UA-Compatible"
      content="IE=edge"
    />
    <meta
      http-equiv="content-type"
      content="text/html; charset=utf-8"
    />
    <meta
      name="google-site-verification"
      content="z7lbN6g7KZtAM12muny0m42sywWxj3dOGrhXDJk9J2I"
    />
    <meta
      name="baidu-site-verification"
      content="vz50FLMDsq"
    />
    <meta
      name="yandex-verification"
      content="167d127030557acc"
    />
    <link
      rel="dns-prefetch"
      href="//cdn.jsdelivr.net"
    />
    <link
      rel="dns-prefetch"
      href="//gravatar.loli.net"
    />
    <link
      rel="profile"
      href="//gmpg.org/xfn/11"
    />
    <link
      rel="alternate"
      href="/assets/jekyll-sitemaps/atom.xml"
      title="RSS"
      type="application/rss+xml"
    />
    <link
      rel="apple-touch-icon-precomposed"
      href="//gravatar.loli.net/avatar/a12c5fff23dde00df79af9aca4e7b6e4?s=300"
    />
    <link
      rel="shortcut
      icon"
      href="//gravatar.loli.net/avatar/a12c5fff23dde00df79af9aca4e7b6e4?s=32"
    />
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/gh/poole/lanyon@ac85a3115c094b3e6cb92cc41771e98b443f6c5d/public/css/poole.min.css"
    />
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/gh/poole/lanyon@ac85a3115c094b3e6cb92cc41771e98b443f6c5d/public/css/lanyon.min.css"
    />
    <link
      rel="stylesheet" href="//cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"
    />
    <script
      src='//cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js' defer='defer'
    ></script>
    <script
      src='//cdn.jsdelivr.net/gh/ghiculescu/jekyll-table-of-contents/toc.min.js'
      defer='defer'
      onload='$(".sidebar-toc").toc()'
    ></script>
    <script
      src='//cdn.jsdelivr.net/npm/simple-jekyll-search/dest/simple-jekyll-search.min.js'
      defer='defer'
      onload='
        SimpleJekyllSearch({
          json: "/assets/simple-jekyll-search/search.json",
          searchInput: document.getElementById("sidebar-search-input"),
          resultsContainer: document.getElementById("sidebar-search-results-container"),
          fuzzy: true
        })'
    ></script>
    <script
      src='//cdn.jsdelivr.net/npm/busuanzi/bsz.pure.mini.min.js'
      defer='defer'
    ></script>
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/npm/katex/dist/katex.min.css"
    />
    <script
      src='//cdn.jsdelivr.net/npm/katex/dist/katex.min.js'
      defer='defer'
    ></script>
    <script
      src='//cdn.jsdelivr.net/npm/katex/dist/contrib/auto-render.min.js'
      defer='defer'
      onload='renderMathInElement(document.body, { delimiters: [{ left: "$", right: "$", display: false }] })'
    ></script>
    <script
      src='//cdn.jsdelivr.net/npm/katex/dist/contrib/mathtex-script-type.min.js'
    defer='defer'></script>
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.css"
    />
    <script
      src='//cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js'
      defer='defer'
      onload='$(".language-mermaid").removeClass("language-mermaid").addClass("mermaid");'
    ></script>
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/npm/prismjs/themes/prism-coy.min.css"
    />
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/npm/prismjs/plugins/line-numbers/prism-line-numbers.min.css"
    />
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/npm/prismjs/plugins/toolbar/prism-toolbar.min.css"
    />
    <script
      src='//cdn.jsdelivr.net/npm/prismjs/components/prism-core.min.js'
      defer='defer'
    ></script>
    <script
      src='//cdn.jsdelivr.net/npm/prismjs/plugins/line-numbers/prism-line-numbers.min.js'
      defer='defer'
      onload='$("pre").addClass("line-numbers")'
    ></script>
    <script
      src='//cdn.jsdelivr.net/npm/prismjs/plugins/autoloader/prism-autoloader.min.js'
      defer='defer'
      onload='Prism.plugins.autoloader.languages_path = "//cdn.jsdelivr.net/npm/prismjs/components/"'
    ></script>
    <script
      src='//cdn.jsdelivr.net/npm/prismjs/plugins/toolbar/prism-toolbar.min.js'
      defer='defer'
      onload='Prism.plugins.toolbar.registerButton("select-code", function (env) {
        var button = document.createElement("button");
        button.innerHTML = "select this " + env.language;
        button.addEventListener("click", function () {
          if (document.body.createTextRange) {
            var range = document.body.createTextRange();
            range.moveToElementText(env.element);
            range.select();
          } else if (window.getSelection) {
            var selection = window.getSelection();
            var range = document.createRange();
            range.selectNodeContents(env.element);
            selection.removeAllRanges();
            selection.addRange(range);
          }
        });
        return button;
        })'
    ></script>
    <script
      src='//cdn.jsdelivr.net/npm/valine'
      defer='defer'
      onload='
        new Valine({
          "el": ".v",
          "appId": "9hABRddSuEkTgqLrt1VSK5B1-gzGzoHsz",
          "appKey": "NJ7RwmgrxsF7KDzlqU7YewlL",
          "notify": "true",
          "verify": "true",
          "avatar": "identicon",
          "placeholder": "在这里评论吧！",
          "visitor": true,
          "highlight": true,
          "avatarForce": false,
          "recordIP": true
        })'
    ></script>
    <link
      rel="stylesheet"
      href="/assets/css/wu-kan.css"
    />
    <script
      src='//cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget/autoload.min.js'
      defer='defer'
    ></script>
    <script
      src='https://buttons.github.io/buttons.js'
      defer='defer'
    ></script>
    <script
      src='https://zz.bdstatic.com/linksubmit/push.js'
      defer='defer'
    ></script>
  # http协议用这个
  # <script
  #   src='http://push.zhanzhang.baidu.com/push.js'
  #   defer='defer'
  # ></script>
